name = "candy-friends-worker"
main = "src/index.ts"
compatibility_date = "2024-08-01"
compatibility_flags = ["nodejs_compat"]
account_id = "8bf1d197a20e59c7aecc54c8ba5b54ba"

[build]
command = "npm run build"

[[durable_objects.bindings]]
name = "GAME_ROOM"
class_name = "GameRoom"

[[durable_objects.migrations]]
tag = "v1"
new_classes = ["GameRoom"]

[exports.GameRoom]
type = "durable-object"
storage = "sqlite"

[observability]
enabled = true

[vars]
ENVIRONMENT = "development"